from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
        def setupUi(self, MainWindow):
                MainWindow.setObjectName("MainWindow")
                MainWindow.resize(1200, 800)
                MainWindow.setStyleSheet("background-color: rgb(58, 58, 58);")
                self.centralwidget = QtWidgets.QWidget(MainWindow)
                self.centralwidget.setObjectName("centralwidget")
                self.name = QtWidgets.QLabel(self.centralwidget)
                self.name.setGeometry(QtCore.QRect(0, 0, 1200, 100))
                font = QtGui.QFont()
                font.setFamily("Purisa")
                font.setPointSize(25)
                font.setBold(True)
                font.setItalic(False)
                font.setWeight(75)
                self.name.setFont(font)
                self.name.setStyleSheet("background-color: rgb(31, 31, 31);\n"
                                        "color: rgb(225, 178, 72);")
                self.name.setScaledContents(True)
                self.name.setAlignment(QtCore.Qt.AlignCenter)
                self.name.setWordWrap(True)
                self.name.setObjectName("name")
                self.star_1 = QtWidgets.QPushButton(self.centralwidget)
                self.star_1.setGeometry(QtCore.QRect(1050, 380, 150, 140))
                font = QtGui.QFont()
                font.setFamily("D050000L")
                font.setPointSize(12)
                font.setBold(True)
                font.setItalic(False)
                font.setWeight(75)
                self.star_1.setFont(font)
                self.star_1.setStyleSheet("background-color: rgb(40, 40, 40);\n"
                                          "color: rgb(225, 178, 72);")
                self.star_1.setObjectName("star_1")
                self.star_2 = QtWidgets.QPushButton(self.centralwidget)
                self.star_2.setGeometry(QtCore.QRect(1050, 520, 150, 140))
                font = QtGui.QFont()
                font.setFamily("D050000L")
                font.setPointSize(12)
                font.setBold(True)
                font.setItalic(False)
                font.setWeight(75)
                self.star_2.setFont(font)
                self.star_2.setStyleSheet("background-color: rgb(40, 40, 40);\n"
"color: rgb(225, 178, 72);")
                self.star_2.setObjectName("star_2")
                self.star_4 = QtWidgets.QPushButton(self.centralwidget)
                self.star_4.setGeometry(QtCore.QRect(1050, 240, 150, 140))
                font = QtGui.QFont()
                font.setFamily("D050000L")
                font.setPointSize(12)
                font.setBold(True)
                font.setItalic(False)
                font.setWeight(75)
                self.star_4.setFont(font)
                self.star_4.setStyleSheet("background-color: rgb(40, 40, 40);\n"
"color: rgb(225, 178, 72);")
                self.star_4.setObjectName("star_4")
                self.star_5 = QtWidgets.QPushButton(self.centralwidget)
                self.star_5.setGeometry(QtCore.QRect(1050, 100, 150, 140))
                font = QtGui.QFont()
                font.setFamily("D050000L")
                font.setPointSize(12)
                font.setBold(True)
                font.setItalic(False)
                font.setWeight(75)
                self.star_5.setFont(font)
                self.star_5.setStyleSheet("background-color: rgb(40, 40, 40);\n"
"color: rgb(225, 178, 72);")
                self.star_5.setObjectName("star_5")
                self.star_3 = QtWidgets.QPushButton(self.centralwidget)
                self.star_3.setGeometry(QtCore.QRect(1050, 660, 150, 140))
                font = QtGui.QFont()
                font.setFamily("D050000L")
                font.setPointSize(12)
                font.setBold(True)
                font.setItalic(False)
                font.setWeight(75)
                self.star_3.setFont(font)
                self.star_3.setStyleSheet("background-color: rgb(40, 40, 40);\n"
"color: rgb(225, 178, 72);")
                self.star_3.setObjectName("star_3")
                self.random = QtWidgets.QPushButton(self.centralwidget)
                self.random.setGeometry(QtCore.QRect(670, 720, 381, 80))
                font = QtGui.QFont()
                font.setFamily("Purisa")
                font.setPointSize(15)
                font.setBold(True)
                font.setItalic(True)
                font.setWeight(75)
                self.random.setFont(font)
                self.random.setStyleSheet("background-color: rgb(40, 40, 40);\n"
"color: rgb(225, 178, 72);")
                self.random.setObjectName("random")
                self.original = QtWidgets.QPushButton(self.centralwidget)
                self.original.setGeometry(QtCore.QRect(0, 720, 331, 80))
                font = QtGui.QFont()
                font.setFamily("Purisa")
                font.setPointSize(15)
                font.setBold(True)
                font.setItalic(True)
                font.setWeight(75)
                self.original.setFont(font)
                self.original.setStyleSheet("background-color: rgb(40, 40, 40);\n"
"color: rgb(225, 178, 72);")
                self.original.setObjectName("original")
                self.aloin = QtWidgets.QPushButton(self.centralwidget)
                self.aloin.setGeometry(QtCore.QRect(330, 720, 341, 80))
                font = QtGui.QFont()
                font.setFamily("Purisa")
                font.setPointSize(15)
                font.setBold(True)
                font.setItalic(True)
                font.setWeight(75)
                self.aloin.setFont(font)
                self.aloin.setStyleSheet("background-color: rgb(40, 40, 40);\n"
"color: rgb(225, 178, 72);")
                self.aloin.setObjectName("aloin")
                self.rewievs = QtWidgets.QLabel(self.centralwidget)
                self.rewievs.setGeometry(QtCore.QRect(0, 100, 1051, 621))
                font = QtGui.QFont()
                font.setFamily("Purisa")
                font.setPointSize(12)
                font.setBold(True)
                font.setWeight(75)
                self.rewievs.setFont(font)
                self.rewievs.setAutoFillBackground(False)
                self.rewievs.setStyleSheet("background-color: rgb(58, 58, 58);\n"
"color: rgb(225, 178, 72);")
                self.rewievs.setTextFormat(QtCore.Qt.AutoText)
                self.rewievs.setScaledContents(True)
                self.rewievs.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
                self.rewievs.setWordWrap(True)
                self.rewievs.setOpenExternalLinks(False)
                self.rewievs.setObjectName("rewievs")
                MainWindow.setCentralWidget(self.centralwidget)

                self.retranslateUi(MainWindow)
                QtCore.QMetaObject.connectSlotsByName(MainWindow)

                self.add_functions()

        def retranslateUi(self, MainWindow):
                _translate = QtCore.QCoreApplication.translate
                MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
                self.name.setText(_translate("MainWindow", "//App"))
                self.star_1.setText(_translate("MainWindow", "444"))
                self.star_2.setText(_translate("MainWindow", "4444"))
                self.star_4.setText(_translate("MainWindow", "44"))
                self.star_5.setText(_translate("MainWindow", "4"))
                self.star_3.setText(_translate("MainWindow", "44444"))
                self.random.setText(_translate("MainWindow", "random"))
                self.original.setText(_translate("MainWindow", "original"))
                self.aloin.setText(_translate("MainWindow", "all on in"))
                self.rewievs.setText(_translate("MainWindow", "sirueoawpdjbgfujdskaswopidfjskajdOIOPA(AIKIOSDJFIOASKDMiejfapsgitrjsakldsigfl;dpgjbfmlvcxl;dasfkdbgl;fdfpofksdlb;,dldspaoksvlvKDOPKODOEFKDASOP"))

        def add_functions(self):
                SDSA


if __name__ == "__main__":
        import sys
        app = QtWidgets.QApplication(sys.argv)
        MainWindow = QtWidgets.QMainWindow()
        ui = Ui_MainWindow()
        ui.setupUi(MainWindow)
        MainWindow.show()
        sys.exit(app.exec_())
